# Generated by Django 4.1.7 on 2023-04-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("receptura", models.CharField(max_length=50)),
                ("godzina_rozpoczecia_zaczynu", models.DateTimeField()),
                ("numer_misy", models.IntegerField()),
                ("temp_zaczynu", models.DecimalField(decimal_places=2, max_digits=5)),
                ("godzina_rozpoczecia_ciasta", models.DateTimeField()),
                ("godzina_konca_ciasta", models.DateTimeField()),
                ("temp_ciasta", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.RemoveField(
            model_name="image",
            name="product",
        ),
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="product",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Image",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
        migrations.DeleteModel(
            name="Stock",
        ),
    ]
