# Generated by Django 4.1.7 on 2023-04-18 12:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_cake_remove_image_product_remove_product_category_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Cake",
        ),
    ]
