# Generated by Django 4.1.7 on 2023-04-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0003_delete_cake"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("project_url", models.URLField()),
                ("github_url", models.URLField()),
                ("technologies", models.CharField(max_length=255)),
            ],
        ),
    ]
