# Generated by Django 4.1.7 on 2023-04-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="project_url",
        ),
        migrations.AddField(
            model_name="project",
            name="rating",
            field=models.IntegerField(default=0),
        ),
    ]
